apiVersion: 1

contactPoints:
  - orgId: 1
    name: Group-4
    disableProvenance: true
    receivers:
      - uid: dft8jhxgfnpj4b
        type: email
        settings:
          addresses: "folatunji@torontomu.ca\ngodspower.amun@torontomu.ca"
          singleEmail: false
        disableResolveMessage: false
